//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public int id { get; set; }
        public int type_id { get; set; }
        public Nullable<int> chest_girth { get; set; }
        public Nullable<int> waist_girth { get; set; }
        public Nullable<int> hip_girth { get; set; }
        public Nullable<int> item_length { get; set; }
        public Nullable<int> sleeve_length { get; set; }
        public Nullable<decimal> result { get; set; }
    
        public virtual Type Type { get; set; }
    }
}
